#!/usr/bin/env python3

class Carbon_Footprint:
    def __init__(self):
        self.lbs_CO2 = 0
        self.kgs_CO2 = 0

        self.household_members = 0
        self.home_size = 0
        self.home_temp = 0
        self.kWh = 0

        # These are the weights it shows 
        # us how much impact each factor has
        # on the amount of CO2 emitted
        self.kWh_weight = 1.06

    def calculate_footprint(self) -> int:
        self.lbs_CO2 = 0
        
        # calculating the amount of CO2
        # emitted through energy consumption
        self.lbs_CO2 += self.kWh * self.kWh_weight

        
        self.kgs_CO2 = self.lbs_CO2/2.20462262
        return self.kgs_CO2, self.lbs_CO2
        # energy usage
        # HVAC
        # Type of house
        # Transportation costs - (Bike/Drive)
        # 
        # Household Members (in real life to be more accurate)
        # All below have to take into account household members  
        # Food bought
        # Appliances - Hang dry clothes, Light bulbs
        # Water Consumption
        # Home size
        # purchases - (clothes, electronics)


        # You feel lucky that you have a decent job
        # as a construction worker for a large corporation,
        # you get decent pay and some benefits

        # The problem? It's located downtown, some 40 minutes
        # from your home. How do you plan to travel today?
        
        # Drive there
        # Take the bus
        # Use your 4 year old bike
