#!/usr/bin/env python3

class Carbon_Footprint:
    def __init__(self):
        self.summer_temperature = 32

        self.carbon_score = 0
        self.lbs_CO2 = 0
        self.kgs_CO2 = 0

        self.household_members = 0
        self.home_size = 0
        self.home_temp = 0
        self.kWh = 0

        # These are the weights it shows 
        # us how much impact each factor has
        # on the amount of CO2 emitted

        # lbs of CO2 per:
        self.kWh_weight = 1.56
        self.members_weight = 206.84
        self.housesize_weight = 1.05
        self.HVAC_weight = 1.8

    # Setter Functions
    def set_household_members(self, n):
        self.household_members = n
    
    def set_home_size(self, n):
        self.home_size = n
    
    def set_home_temp(self, summer_temp):
        self.home_temp = summer_temp

    def calculate_footprint(self) -> int:
        self.lbs_CO2 = 0
        
        # calculating the amount of CO2
        # emitted through energy consumption
        self.lbs_CO2 += self.kWh * self.kWh_weight

        # this takes the number of people in your house
        # and deducts more points based on if you live alone
        # or with others
        self.lbs_CO2 += self.household_members * self.members_weight

        # take the amount of heating and cooling you prefer
        # and calculate how much CO2 you create
        self.lbs_CO2 += ((self.summer_temperature - self.home_temp) * (self.home_size // 1000)) * self.HVAC_weight

        self.kgs_CO2 = self.lbs_CO2/2.20462262
        return self.kgs_CO2, self.lbs_CO2
        # energy usage
        # HVAC
        # Type of house
        # Transportation costs - (Bike/Drive)
        # 
        # Household Members (in real life to be more accurate)
        # All below have to take into account household members  
        # Food bought
        # Appliances - Hang dry clothes, Light bulbs
        # Water Consumption
        # Home size
        # purchases - (clothes, electronics)


        # You feel lucky that you have a decent job
        # as a construction worker for a large corporation,
        # you get decent pay and some benefits

        # The problem? It's located downtown, some 40 minutes
        # from your home. How do you plan to travel today?
        
        # Drive there
        # Take the bus
        # Use your 4 year old bike
    

a = Carbon_Footprint()
